version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: atomic-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: atomic
    volumes:
      - mongo_data:/data/db

  atomic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atomic-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    env_file:
      - .env
    # ⚠️ KHÔNG mount source khi build để tránh ghi đè ./atomic
    # volumes:
    #   - .:/app

volumes:
  mongo_data:
